// ============================================================
// Shared Styles
// ============================================================
// Dark, gritty aesthetic. Fight club meets pub chalk scoreboard.
// Monospace throughout. Mobile-first, max-width 480px.
// ============================================================

export const COLOURS = {
  bg: "#111118",
  bgDark: "#1e1e38",
  primary: "#ff6b35",
  primaryDark: "#e85d26",
  gold: "#f7c948",
  green: "#4ade80",
  red: "#f87171",
  text: "#f0f0f0",
  muted: "#aaa",
  dim: "#888",
  faint: "#777",
  subtle: "#555",
  whatsapp: "#25D366",
};

export const S = {
  app: {
    minHeight: "100vh",
    background: `linear-gradient(180deg, ${COLOURS.bg} 0%, ${COLOURS.bgDark} 50%, ${COLOURS.bg} 100%)`,
    color: COLOURS.text,
    fontFamily: "'Courier New', Courier, monospace",
    position: "relative",
    overflow: "hidden",
  },
  noise: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    opacity: 0.03,
    backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E")`,
    pointerEvents: "none",
    zIndex: 0,
  },
  container: {
    maxWidth: 480,
    margin: "0 auto",
    padding: "20px 16px",
    position: "relative",
    zIndex: 1,
  },
  title: {
    fontSize: 42,
    fontWeight: 900,
    textAlign: "center",
    letterSpacing: -2,
    lineHeight: 1,
    margin: "30px 0 6px",
    background: `linear-gradient(135deg, ${COLOURS.primary} 0%, ${COLOURS.gold} 50%, ${COLOURS.primary} 100%)`,
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    textTransform: "uppercase",
  },
  titleSmall: {
    fontSize: 28,
    fontWeight: 900,
    textAlign: "center",
    letterSpacing: -2,
    lineHeight: 1,
    marginBottom: 4,
    marginTop: 10,
    background: `linear-gradient(135deg, ${COLOURS.primary} 0%, ${COLOURS.gold} 50%, ${COLOURS.primary} 100%)`,
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    textTransform: "uppercase",
  },
  subtitle: {
    textAlign: "center",
    color: COLOURS.dim,
    fontSize: 13,
    letterSpacing: 3,
    textTransform: "uppercase",
    marginBottom: 30,
  },
  card: {
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: 12,
    padding: "20px",
    marginBottom: 16,
    backdropFilter: "blur(10px)",
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: 2,
    color: COLOURS.primary,
    marginBottom: 14,
  },
  input: {
    width: "100%",
    padding: "12px 14px",
    background: "rgba(255,255,255,0.06)",
    border: "1px solid rgba(255,255,255,0.12)",
    borderRadius: 8,
    color: COLOURS.text,
    fontSize: 16,
    fontFamily: "'Courier New', monospace",
    marginBottom: 10,
    boxSizing: "border-box",
    outline: "none",
  },
  inputLarge: {
    width: "100%",
    padding: "20px 14px",
    background: "rgba(255,255,255,0.06)",
    border: "1px solid rgba(255,255,255,0.12)",
    borderRadius: 8,
    color: COLOURS.text,
    fontSize: 28,
    fontFamily: "'Courier New', monospace",
    marginBottom: 10,
    boxSizing: "border-box",
    outline: "none",
    textAlign: "center",
  },
  btnPrimary: {
    width: "100%",
    padding: "14px",
    background: `linear-gradient(135deg, ${COLOURS.primary}, ${COLOURS.primaryDark})`,
    color: "#fff",
    border: "none",
    borderRadius: 8,
    fontSize: 16,
    fontWeight: 700,
    fontFamily: "'Courier New', monospace",
    textTransform: "uppercase",
    letterSpacing: 2,
    cursor: "pointer",
    marginBottom: 8,
  },
  btnSecondary: {
    width: "100%",
    padding: "14px",
    background: "transparent",
    color: COLOURS.primary,
    border: `2px solid ${COLOURS.primary}`,
    borderRadius: 8,
    fontSize: 14,
    fontWeight: 700,
    fontFamily: "'Courier New', monospace",
    textTransform: "uppercase",
    letterSpacing: 2,
    cursor: "pointer",
    marginBottom: 8,
  },
  btnWhatsApp: {
    width: "100%",
    padding: "14px",
    background: "transparent",
    color: COLOURS.whatsapp,
    border: `2px solid ${COLOURS.whatsapp}`,
    borderRadius: 8,
    fontSize: 14,
    fontWeight: 700,
    fontFamily: "'Courier New', monospace",
    textTransform: "uppercase",
    letterSpacing: 2,
    cursor: "pointer",
    marginBottom: 8,
  },
  btnGhost: {
    background: "transparent",
    border: "none",
    color: COLOURS.dim,
    fontSize: 12,
    fontFamily: "'Courier New', monospace",
    cursor: "pointer",
    padding: "8px",
    textDecoration: "underline",
  },
  btnSmall: {
    padding: "8px 14px",
    background: `rgba(255,107,53,0.15)`,
    color: COLOURS.primary,
    border: `1px solid rgba(255,107,53,0.3)`,
    borderRadius: 6,
    fontSize: 12,
    fontWeight: 700,
    fontFamily: "'Courier New', monospace",
    cursor: "pointer",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  btnDanger: {
    padding: "8px 14px",
    background: "rgba(248,113,113,0.15)",
    color: COLOURS.red,
    border: "1px solid rgba(248,113,113,0.3)",
    borderRadius: 6,
    fontSize: 12,
    fontWeight: 700,
    fontFamily: "'Courier New', monospace",
    cursor: "pointer",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  errorMsg: {
    background: "rgba(248,113,113,0.1)",
    border: "1px solid rgba(248,113,113,0.3)",
    borderRadius: 8,
    padding: "10px 14px",
    color: COLOURS.red,
    fontSize: 13,
    marginBottom: 12,
  },
  toast: {
    position: "fixed",
    top: 20,
    left: "50%",
    transform: "translateX(-50%)",
    background: "rgba(255,107,53,0.95)",
    color: "#fff",
    padding: "12px 24px",
    borderRadius: 8,
    fontSize: 14,
    fontWeight: 600,
    zIndex: 100,
    maxWidth: 350,
    textAlign: "center",
    boxShadow: "0 4px 20px rgba(0,0,0,0.5)",
  },
  banterBox: {
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: 12,
    padding: "16px 20px",
    marginBottom: 16,
    fontStyle: "italic",
    color: COLOURS.muted,
    fontSize: 14,
    lineHeight: 1.5,
    textAlign: "center",
  },
  unitToggle: {
    display: "flex",
    gap: 4,
    marginBottom: 10,
  },
  statBox: {
    textAlign: "center",
    flex: 1,
  },
  statVal: {
    fontSize: 28,
    fontWeight: 900,
    color: COLOURS.gold,
    lineHeight: 1,
  },
  statLabel: {
    fontSize: 10,
    color: COLOURS.dim,
    textTransform: "uppercase",
    letterSpacing: 2,
    marginTop: 4,
  },
  nav: {
    display: "flex",
    gap: 4,
    marginBottom: 20,
    flexWrap: "wrap",
  },
  privateBadge: {
    display: "inline-block",
    padding: "2px 8px",
    background: "rgba(255,255,255,0.06)",
    borderRadius: 4,
    fontSize: 10,
    color: COLOURS.muted,
    marginLeft: 8,
  },
  sharedBadge: {
    display: "inline-block",
    padding: "2px 8px",
    background: "rgba(74,222,128,0.1)",
    borderRadius: 4,
    fontSize: 10,
    color: COLOURS.green,
    marginLeft: 8,
  },
  windowBadge: {
    display: "inline-block",
    padding: "2px 8px",
    background: "rgba(247,201,72,0.1)",
    borderRadius: 4,
    fontSize: 10,
    color: COLOURS.gold,
    marginLeft: 8,
  },
  row: {
    display: "flex",
    alignItems: "center",
    padding: "12px 0",
    borderBottom: "1px solid rgba(255,255,255,0.04)",
  },
  divider: {
    height: 1,
    background: "rgba(255,255,255,0.06)",
    margin: "16px 0",
  },
};

// ---- DYNAMIC STYLE HELPERS ----

export const unitBtnStyle = (active) => ({
  flex: 1,
  padding: "8px",
  background: active ? "rgba(255,107,53,0.2)" : "rgba(255,255,255,0.04)",
  border: active
    ? `1px solid ${COLOURS.primary}`
    : "1px solid rgba(255,255,255,0.08)",
  borderRadius: 6,
  color: active ? COLOURS.primary : COLOURS.dim,
  fontSize: 13,
  fontWeight: 700,
  fontFamily: "'Courier New', monospace",
  cursor: "pointer",
  textTransform: "uppercase",
});

export const navBtnStyle = (active) => ({
  flex: "1 1 auto",
  minWidth: 50,
  padding: "10px 4px",
  background: active ? "rgba(255,107,53,0.15)" : "transparent",
  border: active
    ? "1px solid rgba(255,107,53,0.3)"
    : "1px solid rgba(255,255,255,0.06)",
  borderRadius: 8,
  color: active ? COLOURS.primary : COLOURS.dim,
  fontSize: 10,
  fontWeight: 700,
  fontFamily: "'Courier New', monospace",
  cursor: "pointer",
  textTransform: "uppercase",
  letterSpacing: 1,
});

export const lbRowStyle = (isMe, rank) => ({
  display: "flex",
  alignItems: "center",
  padding: "14px 12px",
  borderBottom: "1px solid rgba(255,255,255,0.06)",
  background: isMe
    ? "rgba(255,107,53,0.08)"
    : rank === 0
    ? "rgba(247,201,72,0.06)"
    : "transparent",
});

export const lbRankStyle = (rank) => ({
  width: 32,
  height: 32,
  borderRadius: "50%",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  fontSize: 14,
  fontWeight: 900,
  marginRight: 12,
  flexShrink: 0,
  background:
    rank === 0
      ? `linear-gradient(135deg, ${COLOURS.gold}, ${COLOURS.primary})`
      : rank === 1
      ? "rgba(192,192,192,0.2)"
      : rank === 2
      ? "rgba(205,127,50,0.2)"
      : "rgba(255,255,255,0.06)",
  color: rank === 0 ? "#000" : "#aaa",
});

export const pctStyle = (pctLoss) => ({
  fontSize: 18,
  fontWeight: 900,
  color: pctLoss > 0 ? COLOURS.green : pctLoss < 0 ? COLOURS.red : COLOURS.dim,
  marginLeft: 8,
});

export const paidBtnStyle = (paid) => ({
  padding: "8px 14px",
  background: paid ? "rgba(74,222,128,0.15)" : "rgba(248,113,113,0.15)",
  color: paid ? COLOURS.green : COLOURS.red,
  border: `1px solid ${paid ? "rgba(74,222,128,0.3)" : "rgba(248,113,113,0.3)"}`,
  borderRadius: 6,
  fontSize: 12,
  fontWeight: 700,
  fontFamily: "'Courier New', monospace",
  cursor: "pointer",
  textTransform: "uppercase",
  letterSpacing: 1,
});

export const PLAYER_COLOURS = [
  COLOURS.primary,
  COLOURS.gold,
  COLOURS.green,
  "#60a5fa",
  "#c084fc",
  "#f472b6",
  "#22d3ee",
  "#fb923c",
];
